spring.datasource.url=jdbc:mysql://db:3306/gosmartlib
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.session.cookie.http-only=true
# set to false for development, true for production
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=strict

# CORS allowed origins (dev + prod)
app.cors.allowed-origins=http://localhost:4200,https://gosmartlibs07.tech

server.forward-headers-strategy=framework

smartschool.client-id=2ebf496d131b
smartschool.client-secret=${SMARTSCHOOL_CLIENT_SECRET}
smartschool.redirect-uri=https://gosmartlibs07.tech/auth/callback
